## Problem Set 0  Solutions
### Programming for Economists Autumn 2025: Classes 5 & 9
**Matias BF Hall**

## Contents

1. [Task 1: Installation](#Task-1:-Installation)
2. [Task 2: Understanding code](#Task-2:-Understanding-code)
    * [slicing](#slicing)
    * [references](#references)
    * [loops - breaks](#loops-breaks)
    * [conditionals](#conditionals)
    * [functions and scope](#functions-and-scope)
    * [numpy](#numpy)
    * [classes](#classes)
3. [Task 3: Try Copilot](#Task-3:-Try-Copilot)

## Task 1: Installation

Easiest way to create a jupyter notebook in VSCode is by pressing (Ctrl/Cmd+Shift+P) and running the command "Create: New Jupyter Notebook"

In [12]:
a = 1
b = 2
c = a + b
print(c)
# 3

3


Follow the guide for using Git here: https://sites.google.com/view/numeconcph-progecon/guides/git
And find tips for VSCode here: https://sites.google.com/view/numeconcph-progecon/guides/vscode

## Task 2: Understanding code

#### slicing

In [2]:
x = [0 ,1 ,2 ,3 ,4 ,5]
#defines a list x with six elements

print (x [:2])
# prints a slice of x - the first two elements in x
# [0,1]
print (x [2:])
# prints a slice of x - all elements from index 2 and onwards
# [2,3,4,5]

[0, 1]
[2, 3, 4, 5]


#### references

In [3]:
x = [1 ,2 ,3]
y = x
# y is now a reference to the same list object as x
# changing y will also change x
y[ -1] = 4
print (x)

# y and x are references to the same object in memory so changing y also changes x
# [1,2,4]

# to create a copy of the list x instead of a reference, use the copy() method
x = [1 ,2 ,3]
y = x.copy()
y[ -1] = 4
print (x)

[1, 2, 4]
[1, 2, 3]


##### loops - break

In [4]:
for i in range (5) :
# iterate through numbers 0 to 4 as range starts at 0 and ends at n-1
    if i >= 2: break
    print (i)

# prints all numbers less than 2 because of break which exits the loop when i is 2 or greater
# 0
# 1

0
1


In [5]:
for i in range (5) :
    if i == 2: continue
    print (i)

# does not print anything when i == 2 because of continue which skips the rest of the loop iteration
# 0
# 1
# 3
# 4

0
1
3
4


#### conditionals
[Contents](#Contents)

In [6]:
x = 3
if x > 3:
    print ("too big")
elif x < 1:
    print ("too small")
else :
    print ("just right")
# using conditionals - if, elif and else to check conditions on x
# always use this order - if, elif, else
# if and elif can be used multiple times but else can only be used once as it ends the conditional chain
# else is optional and will always end the conditional chain and be executed if none of the preceding if or elif conditions are true
# if any statement is true, the conditional chain ends and the corresponding block is executed
# prints "just right" because x is neither greater than 3 nor less than 1

just right


#### functions and scope

In [7]:
a = 1
def f(x):
	return x + a  # a is global variable

def g(x, a=1):
	return x + a  # a is local variable
# using def to define functions f() and g()
print(f(1))
print(g(1))
# both will return 2 as f(1) = 1 + 1 and g(1) = 1 + 1 as both the global and local a is 1
a = 2
print(f(1))
# since f() uses the global variable a, it will return 3 as f(1) = 1 + 2 as a is now 2
print(g(1))
# since g() uses its local variable a, it will return 2 as g(1) = 1 + 1 as a is still 1

#Bonus: you can override the local variable a in g() by passing a different value when calling the function
print(g(1, a=2))
# this will return 3 as g(1, a=2) = 1 + 2 as the local variable a is now overridden to be 2

2
2
3
2
3


#### numpy

In [8]:
import numpy as np
x = np.array([1, 2, 3])
y = x
x += 1
print(y)
# y is changed because x and y reference the same object in memory and x is modified
# [2 3 4]
x[:] = x + 1
print(y)
# y is changed because x and y reference the same object in memory and x is modified
# [3 4 5]
x = x + 1
print(y)
# y is not changed because x now references a new object in memory
# [3 4 5]

[2 3 4]
[3 4 5]
[3 4 5]


In [9]:
# use the help function to get documentation on functions and classes
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

#### classes

In [10]:
# Define a class named SquareClass to represent squares.
class SquareClass:
	# The __init__ method is a special method called a constructor. It is automatically
    # invoked when a new instance of the class is created. The purpose of this method
    # is to initialize the newly created object's state.
	def __init__(self, length, width):
		# `self` represents the instance of the class. It is the first argument to the
        # methods of a class. Using `self`, we can access the attributes and methods of
        # the class in Python. It binds the attributes with the given arguments.
        
        # `self.length` and `self.width` are instance variables. They are being
        # initialized with the values passed to the __init__ method upon the object's
        # creation. This allows each instance of SquareClass to have its own length and
        # width values.
		self.length = length
		self.width = width
	 # This is an instance method that calculates and returns the area of the square.
    # Instance methods need a reference to the specific object instance (self) to access
    # its attributes and other methods. This method uses `self.length` and `self.width`
    # to access the square's length and width that were stored in the instance variables
    # when the object was instantiated.
	def size(self):
		return self.length * self.width

# Creating an instance (object) of the SquareClass. This action calls the __init__ method
# of SquareClass with `length=2` and `width=2`, initializing the new square object's
# attributes with these values. The variable `square` now refers to this new object.
square = SquareClass(2, 2)
print(square.size())
#square.size() calls the method size() of the object square which returns length * width
# 4

4


## Task 3: Try Copilot

[Contents](#Contents)

* To accept automatic Copilot code use "Tab"
* To reject automatic Copilot code use "Esc"

In [11]:
import numpy as np
x = np. array ([2 ,5 ,10 ,2 ,4])
# sort and print x

# Here is what my Copilot suggested:
x.sort()
print(x)

[ 2  2  4  5 10]


Open chat by pressing (Ctrl+Alt+B). Try to type in "plot x vs log(x)"

For better learning and understanding, it is a good idea to pause copilot when doing problem sets. Do so by clicking the "frog" in the bottom right of VSCode and pausing or disabling temporary.